
# Site settings

title: Adel Lamallam
email: contact@afroware.com
description: > 
  This is my open source project home page, here you will find 
  documentations, blog, discutions about differents kind of releases.
baseurl: "/"
url: "https://afroware.com"
twitter_username: afroware
github_username:  alamallam

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
